import { Poppins, Roboto } from 'next/font/google';
import EBReactScan from './common/common/components/EBReactScan';
import SessionProviders from './login/common/store/sessionprovider';
import type { Metadata } from 'next';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'EchoBoard',
  description: 'Generated by create next app',
};

export default function rootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <EBReactScan />
      <head>
        <link
          href='https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css'
          rel='stylesheet'
        />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${poppins.variable} ${roboto.variable} antialiased`}
      >
        <SessionProviders>{children}</SessionProviders>
      </body>
    </html>
  );
}
