import { Comment, Question, ProfileData } from './types';

export const sampleQuestion: Question = {
  id: 'question-1',
  avatar: 'https://i.pravatar.cc/150?img=6',
  name: 'User 2',
  message: 'What is the best morning diet?',
  timestamp: '2023-10-01T12:34:56Z',
  likes: 12,
  dislikes: 2,
  comments: 5,
};

export const sampleComments: Comment[] = [
  {
    id: 'comment-1',
    avatar: 'https://i.pravatar.cc/150?img=1',
    name: 'User 1',
    message: 'I recommend a balanced diet with fruits and nuts.',
    timestamp: '2023-10-01T13:34:56Z',
    likes: 12,
    dislikes: 2,
    comments: 2,
    replies: [
      {
        id: 'reply-1',
        avatar: 'https://i.pravatar.cc/150?img=2',
        name: 'User 2',
        message: 'I agree! Fruits are essential for vitamins.',
        timestamp: '2023-10-01T14:34:56Z',
        likes: 0,
        dislikes: 0,
        comments: 0,
      },
      {
        id: 'reply-2',
        avatar: 'https://i.pravatar.cc/150?img=3',
        name: 'User 3',
        message: 'What about protein sources?',
        timestamp: '2023-10-01T15:34:56Z',
        likes: 0,
        dislikes: 0,
        comments: 0,
      },
    ],
  },
  {
    id: 'comment-2',
    avatar: 'https://i.pravatar.cc/150?img=4',
    name: 'User 4',
    message: 'A high-protein breakfast is the best!',
    timestamp: '2023-10-01T16:34:56Z',
    likes: 8,
    dislikes: 1,
    comments: 1,
    replies: [
      {
        id: 'reply-3',
        avatar: 'https://i.pravatar.cc/150?img=5',
        name: 'User 5',
        message: 'Eggs are a great source of protein.',
        timestamp: '2023-10-01T17:04:56Z',
        likes: 0,
        dislikes: 0,
        comments: 0,
      },
    ],
  },
  {
    id: 'comment-3',
    avatar: 'https://i.pravatar.cc/150?img=6',
    name: 'User 6',
    message: 'Don’t forget to hydrate! Drink plenty of water in the morning.',
    timestamp: '2023-10-01T17:19:56Z',
    likes: 5,
    dislikes: 0,
    comments: 1,
    replies: [
      {
        id: 'reply-4',
        avatar: 'https://i.pravatar.cc/150?img=7',
        name: 'User 7',
        message: 'Yes, hydration is key!',
        timestamp: '2023-10-01T17:34:56Z',
        likes: 0,
        dislikes: 0,
        comments: 0,
      },
    ],
  },
  {
    id: 'comment-4',
    avatar: 'https://i.pravatar.cc/150?img=8',
    name: 'User 8',
    message: 'Oatmeal with fruits is my go-to breakfast.',
    timestamp: '2023-10-01T17:44:56Z',
    likes: 10,
    dislikes: 1,
    comments: 1,
    replies: [
      {
        id: 'reply-5',
        avatar: 'https://i.pravatar.cc/150?img=9',
        name: 'User 9',
        message: 'Same here! It’s so filling and healthy.',
        timestamp: '2023-10-01T17:54:56Z',
        likes: 0,
        dislikes: 0,
        comments: 0,
      },
    ],
  },
  {
    id: 'comment-5',
    avatar: 'https://i.pravatar.cc/150?img=10',
    name: 'User 10',
    message: 'Smoothies are a great way to start the day!',
    timestamp: '2023-10-01T18:04:56Z',
    likes: 7,
    dislikes: 0,
    comments: 1,
    replies: [
      {
        id: 'reply-6',
        avatar: 'https://i.pravatar.cc/150?img=11',
        name: 'User 11',
        message: 'What’s your favorite smoothie recipe?',
        timestamp: '2023-10-01T18:07:56Z',
        likes: 0,
        dislikes: 0,
        comments: 0,
      },
    ],
  },
];

export const profileData: ProfileData = {
  avatar: 'https://i.pravatar.cc/150?img=1',
  username: 'darkknight777',
  email: 'darkknight777@gmail.com',
  points: 457,
};
