name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: "Check for Vulnerabilities"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          echo "Checking for vulnerabilities in SonarQube..."
          
          # Fetch the number of vulnerabilities
          VULNERABILITIES=$(curl -s -u $SONAR_TOKEN: \
            "$SONAR_HOST_URL/api/issues/search?componentKeys=my-project&types=VULNERABILITY&resolved=false" \
            | jq -r '.total')

          echo "Detected Vulnerabilities: $VULNERABILITIES"

          # Fail if any vulnerabilities are found
          if [ "$VULNERABILITIES" -gt 0 ]; then
            echo "❌ SonarCloud detected vulnerabilities! Failing the workflow."
            exit 1
          fi

          echo "✅ No vulnerabilities found. Proceeding with workflow."
